# https://www.osbuild.org/guides/blueprint-reference/blueprint-reference.html

#
# Base definition
#
name = "base-image"
description = "Base Image"
version = "2021.12.02"
distro = "rhel-85"

#
# Boot parameters
#
[customizations.kernel]
append = "net.ifnames.prefix=net ipv6.disable=0 quiet systemd.show_status=yes"

#
# Filesystem
#
[[customizations.filesystem]]
mountpoint = "/"
size = 8589934592
[[customizations.filesystem]]
mountpoint = "/home"
size = 1073741824
[[customizations.filesystem]]
mountpoint = "/var"
#size = 8589934592
[[customizations.filesystem]]
mountpoint = "/var/log"
size = 2147483648
[[customizations.filesystem]]
mountpoint = "/var/log/audit"
size = 1073741824
[[customizations.filesystem]]
mountpoint = "/var/tmp"
size = 1073741824
[[customizations.filesystem]]
mountpoint = "/opt"
size = 4294967296

#
# Locale
#
[customizations.locale]
languages = ["en_US.UTF-8"]
keyboard = "dk"

#
# Timezone
#
[customizations.timezone]
timezone = "Europe/Copenhagen"
ntpservers = ["time.cloudflare.com"]

#
# Services
#
[customizations.services]
enabled = ["sshd", "systemd-resolved", "tuned"]

#
# Firewall
#
[customizations.firewall.services]
enabled = ["ssh"]

#
# Packages
#
[[packages]]
name = "bash-completion"
version = "*"
[[packages]]
name = "bzip2"
version = "*"
[[packages]]
name = "chrony"
version = "*"
[[packages]]
name = "firewalld"
version = "*"
[[packages]]
name = "man-pages"
version = "*"
[[packages]]
name = "openssh-clients"
version = "*"
[[packages]]
name = "policycoreutils-python-utils"
version = "*"
[[packages]]
name = "prefixdevname"
version = "*"
[[packages]]
name = "psmisc"
version = "*"
[[packages]]
name = "python3"
version = "*"
[[packages]]
name = "python3-libselinux"
version = "*"
[[packages]]
name = "setools-console"
version = "*"
[[packages]]
name = "tar"
version = "*"
[[packages]]
name = "tuned"
version = "*"
[[packages]]
name = "virt-what"
version = "*"
[[packages]]
name = "yum-utils"
version = "*"

#
# Security compliance
#
#[[packages]]
#name = "aide"
#version = "*"
#[[packages]]
#name = "openscap"
#version = "*"
#[[packages]]
#name = "openscap-scanner"
#version = "*"
#[[packages]]
#name = "scap-security-guide"
#version = "*"

#
# Root
#
[[customizations.sshkey]]
user = "root"
key = "ssh-rsa sh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDB4v1PvoxDFpycdXL8HRay9MkCBqURFDwKIrDCMAJCKsCytLSx8dcMQn15d4eTQzSm30DLCvpMYYLUAdmsoH10FNvVCKaXGzPgX+ONz1Zb+XcoL3yBM2ALAtIXzUiEChCPu60WMDeDmTwQYukqW9TsWTF+MSIkn9hv2VSZ74IUL+vh8x97+OVw4ASmXsPBVGOkwnj/Fwfaxb1uXmfytBgOKCaASnDO0UXJ8DIn5kDlp+keXzdauT/6pL9orUDWSncyK728oeNbqFJBYCj6aTV2a6lCQQwwvYXzLpIUkKfTk/Hgqyum2I6HZItiNclyqSLgssxO/YR5AZqlVlm58vdd ansible-generated on virtual"

#
# User
#
[[customizations.user]]
name = "ansinst"
key = "sh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDB4v1PvoxDFpycdXL8HRay9MkCBqURFDwKIrDCMAJCKsCytLSx8dcMQn15d4eTQzSm30DLCvpMYYLUAdmsoH10FNvVCKaXGzPgX+ONz1Zb+XcoL3yBM2ALAtIXzUiEChCPu60WMDeDmTwQYukqW9TsWTF+MSIkn9hv2VSZ74IUL+vh8x97+OVw4ASmXsPBVGOkwnj/Fwfaxb1uXmfytBgOKCaASnDO0UXJ8DIn5kDlp+keXzdauT/6pL9orUDWSncyK728oeNbqFJBYCj6aTV2a6lCQQwwvYXzLpIUkKfTk/Hgqyum2I6HZItiNclyqSLgssxO/YR5AZqlVlm58vdd ansible-generated on virtual"
home = "/home/rexuser"
shell = "/bin/bash"
groups = ["users", "wheel"]
